name: Branch Validation

on:
  create:
    branches:
      - '*'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|release)/ ]]; then
            echo "Invalid branch name prefix: $BRANCH_NAME. Must be one of 'feature|bugfix|release'."
            exit 1
          fi
